### ISSUE TITLE
Address display not according to design

### ISSUE THREAD

**Issue by radicleart** [stacks-network/sbtc-bridge-web#176]
The address is not displayed according to design.

See [slack](https://stacks-builders.slack.com/archives/C05F7F6A9SL/p1687899378712749)

![](https://files.slack.com/files-pri/T05093RKWEP-F05EWHCAS81/image.png)

**Comment by radicleart** [comment]
@Macxim - the problem here is the taproot address s very long - it looks like ths when dropping to text-xs (from sm) - any suggestions ?


![Screenshot 2023-07-02 at 12 34 40](https://github.com/Stacks-Builders/sbtc-bridge-web/assets/4384929/534d4eab-db0e-4760-8553-74b56b2e3147)

**Comment by Macxim** [comment]
I really don't mind truncating the address. @radicleart 
It was fine for me to be honest.

**Comment by Macxim** [comment]
What I would change here is the behavior of copying something to the clipboard though.
That yellow highlighting doesn't look very good.

I suggest something like this:

https://github.com/Stacks-Builders/sbtc-bridge-web/assets/1909957/3dacb864-9404-43cf-a34d-453afc36386e

**Comment by radicleart** [comment]
fixed by other work
