### ISSUE TITLE
Fix Currency dropdown select logic in Settings page

### ISSUE THREAD

**Issue by Macxim** [stacks-network/sbtc-bridge-web#207]
![Screenshot 2023-08-14 at 11 37 31](https://github.com/Stacks-Builders/sbtc-bridge-web/assets/1909957/9d44972f-474e-47a7-9744-4d1d50c71293)

**Comment by radicleart** [comment]
@Macxim is this fixed ?

**Comment by Macxim** [comment]
I don't think so, no.

**Comment by radicleart** [comment]
Fixed now @Macxim ?

**Comment by Macxim** [comment]
Let me check

**Comment by Macxim** [comment]
Seems so, yeah. Good job!
