### ISSUE TITLE
Add analysis for fulfillment btc tx

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-web#268]
Txs like 4c7628f7a5c50c23f1c1d6038d72d9624e1ff9e7f9d3613aa64772c19721e82f (on testnet) should be shown as fulfillment btc txs

**Comment by radicleart** [comment]
Can you remind me the technique you mentioned for locating these ?

one idea..
 
- read stacks burn event, 
- read the withdraw request txid
- get the fulfil address (2nd output)
- read transactions to that address and find the one with
   - correct opcode in op_return
   - matching amount

record the txid and display as fulflment ?

**Comment by friedger** [comment]
It is probably enough to search for a FulfillBroadcasted event with the bitcoin request tx in it and then use the bitcoin txid of the fulfillBroadcasted event.

**Comment by radicleart** [comment]
question is where to search for this event? The bridge has no access to romeo events?

**Comment by friedger** [comment]
The signer has an rpc api. Maybe we will continue from there.
