### ISSUE TITLE
Don't hide button when Bitcoin input field errors

### ISSUE THREAD

**Issue by Macxim** [stacks-network/sbtc-bridge-web#282]
Hiding content, especially action button is not very good UX-wise.
Buttons should be always visible and users should be able to click them and see why it fails.

https://github.com/stacks-network/sbtc-bridge-web/assets/1909957/585e15f0-00ea-4759-a007-4c251c37fdc9

**Comment by radicleart** [comment]
how about adding disabled ? Plus the error message.

**Comment by radicleart** [comment]
done - didn't change the button color but did make it disabled to prevent flow from proceding.
