### ISSUE TITLE
Remove references to op_drop

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-web#285]
Currently, sbtc binary only supports op_return

![image](https://github.com/stacks-network/sbtc-bridge-web/assets/1449049/c2b28a1c-3c9c-4d57-bdd5-a5a5f2dc1f34)

**Comment by radicleart** [comment]
Thanks.

**Comment by radicleart** [comment]
done - except i left the op_drop button but with a warning. the reason for this was if anyone had clicked it and was exploring op_drop they would have been stuck with it after this release.
