### ISSUE TITLE
Wrong social media icons

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-web#287]
In the footer, the twitter icon links to discord, the github icon links to X

![image](https://github.com/stacks-network/sbtc-bridge-web/assets/1449049/a49799ef-ec2f-4b77-8829-da72e18f56ea)

**Comment by Macxim** [comment]
Easy fix. I can take that @radicleart if you want.

**Comment by radicleart** [comment]
done already - picked up all these issues..

**Comment by radicleart** [comment]
> Easy fix. I can take that @radicleart if you want.

already done !

**Comment by radicleart** [comment]
done
