### ISSUE TITLE
Add deeplink for any bitcoin request tx

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-web#290]
The details for a bitcoin tx (https://mempool.space/testnet/tx/685e9a1b065eb4380c600d5d58d9f840aafe1dd002cee0f619a38a5a9e3397fc is shown as:

`https://bridge.sbtc.tech/transactions/653b7c1069afb0f54fecc57b?chain=testnet`

However, I don't know how to see the details of btc tx 92a78bf5614cf17372b758da60aafed9726332eecde269bbc31ca37527264423

The bridge should support deep links like this:

`https://bridge.sbtc.tech/transactions/92a78bf5614cf17372b758da60aafed9726332eecde269bbc31ca37527264423?chain=testnet`

If no data available, show a nice 404 :-)

**Comment by radicleart** [comment]
done
