### ISSUE TITLE
updates are slow or broken?

### ISSUE THREAD

**Issue by dantrevino** [stacks-network/sbtc-bridge-web#315]
Sent testnet btc to the contract via the ui at https://bridge.sbtc.tech/.  My balances have not been updated for over 9 hrs on the site, however, my stacks account balances show the process worked.  Tried multiple hard reloads, clear cache, different browsers.

btc txn:
https://mempool.space/testnet/tx/e81b6141df9ff31cb25d756a305a0aa47c97518bdb46c7e1d7e6963a16ba6612

stacks account balances:
https://api.testnet.hiro.so/extended/v1/address/ST2RTE7F21N6GQ6BBZR7JGGRWAT0T5Q3Z9XX4TC3R/balances

**Comment by radicleart** [comment]
Thanks fro reporting @dantrevino .

This is with Xverse ? Did you also disconnect / reconnect wallet ?

**Comment by radicleart** [comment]
Closing as stale
